#kirin:
#  provider:
#    enable: true
#    name: providerName
#    registry-address: 127.0.0.1:2181
#    provider-port: 7070
#    provider-address: 127.0.0.1
#  consumer:
#    name: consumerName
#    registry-address: 127.0.0.1:2181

logging:
  level:
    io.github.nnkwrik.kirinrpc: debug
    org.springframework.beans.factory: debug
